### ISSUE TITLE
Is it working example?

### ISSUE THREAD

**Issue by ivanbalashov239** [synasius/qt-custom-keyboard-proof#1]
Hi, have you checked functionality of it? Is it working proof?

**Comment by synasius** [comment]
Hi! Yes it's a working example.
At the time I was testing V-Play so the app uses that framework as a base, but the keyboard code is not tied to vplay. You should be able to use it in a vanilla Qt project

**Comment by ivanbalashov239** [comment]
@synasius great news, thanks.

**Comment by ivanbalashov239** [comment]
@synasius i've made it work with v-play, and it's not providing qt/qml activity to draw custom keyboard, do you have thoughts/knowledge how to do that?
